import express, { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import { asyncHandler, authenticate } from '../common/middleware/error.middleware.js';

const router = express.Router();
const prisma = new PrismaClient();

// Get all segments
router.get('/', authenticate, asyncHandler(async (req: Request, res: Response) => {
  const { organizationId } = (req as any).user;
  
  const segments = await prisma.segment.findMany({
    where: { organizationId },
    orderBy: { createdAt: 'desc' }
  });
  
  res.json({ segments });
}));

// Create segment
router.post('/', authenticate, asyncHandler(async (req: Request, res: Response) => {
  const { organizationId } = (req as any).user;
  const { name, description, criteria, color } = req.body;
  
  const segment = await prisma.segment.create({
    data: {
      organizationId,
      name,
      description,
      criteria,
      color,
      isAutoGenerated: false
    }
  });
  
  res.status(201).json({ segment });
}));

// Auto-generate segments based on criteria
router.post('/auto-generate', authenticate, asyncHandler(async (req: Request, res: Response) => {
  const { organizationId } = (req as any).user;
  
  // Get profile counts
  const profiles = await prisma.userProfile.groupBy({
    by: ['engagementScore'],
    where: { organizationId },
    _count: true
  });
  
  const segments = [
    { name: 'New Users', criteria: { visitCount: { lte: 2 } }, color: '#8B5CF6', description: 'Users with 2 or fewer visits' },
    { name: 'Active Users', criteria: { engagementScore: { gte: 20, lt: 60 } }, color: '#10B981', description: 'Regularly engaged users' },
    { name: 'High Value', criteria: { engagementScore: { gte: 60 } }, color: '#F59E0B', description: 'Highly engaged users' },
    { name: 'At Risk', criteria: { lastActiveAt: { gt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000) } }, color: '#F43F5E', description: 'Inactive for 14+ days' }
  ];
  
  const results = [];
  for (const seg of segments) {
    const count = await prisma.userProfile.count({
      where: { organizationId, ...seg.criteria as any }
    });
    
    let segment = await prisma.segment.findFirst({
      where: { organizationId, name: seg.name }
    });
    
    if (!segment) {
      segment = await prisma.segment.create({
        data: {
          organizationId,
          name: seg.name,
          description: seg.description,
          criteria: seg.criteria,
          color: seg.color,
          userCount: count,
          isAutoGenerated: true
        }
      });
    } else {
      segment = await prisma.segment.update({
        where: { id: segment.id },
        data: { userCount: count }
      });
    }
    
    results.push(segment);
  }
  
  res.json({ segments: results });
}));

// Update segment
router.put('/:id', authenticate, asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;
  const { organizationId } = (req as any).user;
  const { name, description, criteria, color } = req.body;
  
  const segment = await prisma.segment.update({
    where: { id, organizationId },
    data: { name, description, criteria, color }
  });
  
  res.json({ segment });
}));

// Delete segment
router.delete('/:id', authenticate, asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;
  const { organizationId } = (req as any).user;
  
  await prisma.segment.delete({
    where: { id, organizationId }
  });
  
  res.json({ success: true });
}));

export default router;